---
- hosts: all
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - python-pip
        - ubuntu-desktop
    - name: Install pips
      pip: name={{ item }}
      with_items:
        - pip
